linters-settings:
  errcheck:
    check-type-assertions: true
  goimports:
    local-prefixes: github.com/moycat/vaar
  nolintlint:
    require-explanation: true
    require-specific: true

linters:
  disable-all: true
  enable:
    - bodyclose
    - deadcode
    - depguard
    - dogsled
    - dupl
    - errcheck
    - errorlint
    - exportloopref
    - exhaustive
    - godot
    - gofmt
    - goimports
    - gocyclo
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - prealloc
    - predeclared
    - revive
    - staticcheck
    - structcheck
    - stylecheck
    - thelper
    - tparallel
    - typecheck
    - unconvert
    - unparam
    - varcheck
    - whitespace

issues:
  fix: true
  new: true
  exclude-rules:
    - path: _test\.go # disable some linters for test files
      linters:
        - gocyclo
        - gosec
        - dupl
    - linters:
        - gosec
      text: "weak cryptographic primitive"

  max-issues-per-linter: 0
  max-same-issues: 0

run:
  issues-exit-code: 1